# -*- coding: utf-8 -*-
"""sales_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KRApfzN8bNidpEkLmZ2e-OFuA5PXMpYQ

Upload Dataset
"""

from google.colab import files
uploaded = files.upload()

"""Load Dataset"""

import pandas as pd

df = pd.read_csv("retail_sales_dataset.csv")
df.head()

"""Data Cleaning"""

df.info()
df.isnull().sum()

df.dropna(inplace=True)

"""Convert Date column to datetime and Ensure numeric columns are correct


"""

df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
df['Quantity'] = pd.to_numeric(df['Quantity'])
df['Price per Unit'] = pd.to_numeric(df['Price per Unit'])
df['Total Amount'] = pd.to_numeric(df['Total Amount'])

"""Total sales

"""

total_sales = df['Total Amount'].sum()
print("Total Sales:", total_sales)

"""Sales by product category

"""

sales_by_category = df.groupby('Product Category')['Total Amount'].sum()
print(sales_by_category)

"""Average purchase per customer

"""

avg_purchase = df.groupby('Customer ID')['Total Amount'].mean()
print(avg_purchase.head())

"""Sales by gender

"""

sales_by_gender = df.groupby('Gender')['Total Amount'].sum()
print(sales_by_gender)

"""Sales by age group

"""

df['Age Group'] = pd.cut(df['Age'], bins=[18,30,40,50,60,70], labels=['18-30','31-40','41-50','51-60','61-70'])
sales_by_age = df.groupby('Age Group')['Total Amount'].sum()
print(sales_by_age)

"""Monthly sales trend

"""

df['Month'] = df['Date'].dt.month
monthly_sales = df.groupby('Month')['Total Amount'].sum()

import matplotlib.pyplot as plt
monthly_sales.plot(kind='bar', title="Monthly Sales")
plt.show()

"""Top 10 products by revenue

"""

top_products = df.groupby('Product Category')['Total Amount'].sum().sort_values(ascending=False)
top_products.plot(kind='bar', title="Top Product Categories")
plt.show()

"""Average spend per transaction

"""

avg_transaction = df['Total Amount'].mean()
print("Average Transaction Value:", avg_transaction)

"""High-value customers (top 10)

"""

top_customers = df.groupby('Customer ID')['Total Amount'].sum().sort_values(ascending=False).head(10)
print(top_customers)
